services:
  web:
    ports:
      - "8000:80"
    volumes:
      - ./infra/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
  app:
    build:
      context: ./infra/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./infra/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      XDEBUG_MODE: debug,coverage
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003