services:
    app:
        build:
            context: ./infra/php
        volumes:
            - ./src:/var/www/html
            - ./infra/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        environment:
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
            - APP_URL=${APP_URL}
            - APP_KEY=${APP_KEY}
            - XDEBUG_MODE=off
        networks:
            - laravel

    web:
        image: nginx:alpine
        volumes:
            - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
            - /etc/letsencrypt:/etc/letsencrypt:ro
        ports:
            - "80:80"
            - "443:443"
        networks:
            - laravel
        depends_on:
            - app

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge