services:
    app:
        build:
            context: ./infra/php
        volumes:
            - ./src:/var/www/html
        environment:
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=db
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
            - APP_URL=${APP_URL}
            - APP_KEY=${APP_KEY}
            - XDEBUG_MODE=off
        networks:
            - laravel
        depends_on:
            - db

    web:
        image: nginx:alpine
        volumes:
            - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
            - /etc/letsencrypt:/etc/letsencrypt:ro
        ports:
            - "80:80"
            - "443:443"
        networks:
            - laravel
        depends_on:
            - app

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "${DB_PORT}:${DB_PORT}"
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge